/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InsertionSort {
    }
}
declare global {
    interface HTMLInsertionSortElement extends Components.InsertionSort, HTMLStencilElement {
    }
    var HTMLInsertionSortElement: {
        prototype: HTMLInsertionSortElement;
        new (): HTMLInsertionSortElement;
    };
    interface HTMLElementTagNameMap {
        "insertion-sort": HTMLInsertionSortElement;
    }
}
declare namespace LocalJSX {
    interface InsertionSort {
    }
    interface IntrinsicElements {
        "insertion-sort": InsertionSort;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "insertion-sort": LocalJSX.InsertionSort & JSXBase.HTMLAttributes<HTMLInsertionSortElement>;
        }
    }
}
